############################################
#	TurnBattle_PHP/Makefile
############################################

1st:
	php -l Main.php
	php -l TurnBattle.php
	php -l Character.php
	php -l Utility.php
	php -l Command.php
	php -l UI.php
	php -l AI.php
	php Main.php
